development:
  cloud_name: ENV['CLOUD_NAME']
  api_key: ENV['CLOUD_API_KEY']
  api_secret: ENV['CLOUD_API_SECRET']
  secure: true

production:
  cloud_name: CLOUD_NAME
  api_key: CLOUD_API_KEY
  api_secret: CLOUD_API_SECRET
  secure: true
